version: 2
updates:
  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/' # location of package.json
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    labels:
      - 'dependencies'
      - 'npm'
    ignore:
      # Block all major updates for every package
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github-actions'
    ignore:
      # Block all major updates for GitHub Actions
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
