services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env
