services:
  backend:
    container_name: backend_dev
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.Dev
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=developmnt
      - PORT=8080
    env_file:
      - .env
