services:
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: on-failure
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - template-server-network

  server-dev:
    depends_on:
      - redis
    container_name: template-server-dev
    build:
      context: .
      dockerfile: Dockerfile.Dev
    restart: on-failure
    volumes:
      - ./src:/app/src
      - ./eslint.config.mjs:/app/eslint.config.mjs
      - ./eslint.airbnb.mjs:/app/eslint.airbnb.mjs
      - ./.prettierignore:/app/.prettierignore
      - ./.prettierrc:/app/.prettierrc
      - ./vitest.config.ts:/app/vitest.config.ts
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./tsconfig.json:/app/tsconfig.json
      - ./logs:/app/logs
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
      - REDIS_HOST=redis
    env_file:
      - .env
    networks:
      - template-server-network

networks:
  template-server-network:
    driver: bridge

volumes:
  redis-data:
