on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

# cancel any previous runs in progress for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          target-branch: ${{ github.ref_name }}
